title: 欢迎!
author: 烧饼
email: sbgetvpn@gmail.com
url: https://sbget.com
baseurl: "/no-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)

theme: jekyll-theme-tactile
